version: 3

dotenv: [ '.env', '{{.ENV}}/.env.', '{{.HOME}}/.env' ]

# Dynamic variables for the task runners
vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  GIT_REPO:
    sh: git config --get remote.origin.url | sed -e 's#^.*:##' -e 's#.git$##' -e 's#//github.com/*##'
  GIT_REPO_NAME:
    sh: echo {{.GIT_REPO}} | sed -e 's#^.*/##'
  GIT_OWNER:
    sh: echo {{.GIT_REPO}} | sed -e 's#/.*$##'
  SPACELIFT_DOCKER_FILE: ops/spacelift-runner/Dockerfile
  SPACELIFT_RUNNER_IMAGE: ghcr.io/loadsure/spacelift-runner:latest

silent: true

tasks:
  default:
    cmds:
      - task --list

  lint:
    desc: Run hadolint and tflint
    cmds:
      - hadolint {{ .SPACELIFT_DOCKER_FILE }}

  sec:
    desc: Run trivy security checks
    cmds:
      - trivy config .

  sec:ci:
    desc: Run trivy security checks in CI mode
    cmds:
      - trivy config . --format sarif --output trivy.sarif.json

  build:
    desc: Build the Spacelift Docker image
    cmds:
      - docker build --platform linux/amd64 -t {{ .SPACELIFT_RUNNER_IMAGE }} . -f {{ .SPACELIFT_DOCKER_FILE }}
      - trivy image {{ .SPACELIFT_RUNNER_IMAGE }}

  push:
    desc: Push the Spacelift Docker image to the registry
    cmds:
      - docker push {{ .SPACELIFT_RUNNER_IMAGE }}
